version: '3'
services:
  main:
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    build:
      context: ./main-server
    environment:
      - PORT=3000
      - ACCESS_TOKEN_SECRET_KEY=E1Ohyo1FA6Fnw7YOO6w0
      - REFRESH_TOKEN_SECRET_KEY=tMXauVcURzLObtt0IfBE
      - DB_NAME=jabama_main
      - DB_HOST=mongodb://mongo:27017
      - RABBITMQ_URL=amqp://rabbitmq:5672
    ports:
      - 80:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
      - rabbitmq_data:/var/log/rabbitmq/log
  mail: 
    build:
      context: ./mail-server
    depends_on:
      - rabbitmq
    restart: always
    environment:
      - SENDGRID_NOREPLY_EMAIL=no-reply@igmu.app
      - RABBITMQ_URL=amqp://rabbitmq:5672
  logger: 
    build:
      context: ./logger-server
    depends_on:
      - rabbitmq
      - mongo
    restart: always
    environment:
      - DB_NAME=jabama_logs
      - DB_HOST=mongodb://mongo:27017
      - RABBITMQ_URL=amqp://rabbitmq:5672
volumes:
 mongodb:
 rabbitmq_data: